version: '3.8'

services:
  # Veritabanı Servisi
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Captainstore123."
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql

  # Mesaj kuyruğu servisi
  rabbitmq:
    &rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672

  # Caching servisi
  redis:
    &redis
    image: redis:latest
    ports:
      - 6379:6379

  # Loglama servisi
  seq:
    &seq
    image: datalust/seq
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y

  # Arama servisi
  elasticsearch:
    &elasticsearch
    image: elasticsearch:8.14.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  # Arama görsel servisi
  kibana:
    &kibana
    image: kibana:8.14.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

  # API Servisleri
  api:
    build:
      context: ../Presentation/Papara.CaptainStore.API
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqlserver,1433;Database=CaptainStore;User ID=SA;Password=Captainstore123.;

  paymentapi:
    build:
      context: ../Papara.CaptainStore.PaymentAPI
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqlserver,1433;Database=CaptainStore;User ID=SA;Password=Captainstore123.;


volumes:
  elasticsearch-data:
    driver: local
  sqlserver_data:
    driver: local