version: '3.8'

services:
  redis:
    &redis
    image: redis:latest
    ports:
      - 6379:6379

  rabbitmq:
    &rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672

  seq:
    &seq
    image: datalust/seq
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y

  elasticsearch:
    &elasticsearch
    image: elasticsearch:8.14.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    &kibana
    image: kibana:8.14.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

  sqlserver:
    &sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Captainstore123."
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  elasticsearch-data:
    driver: local
  sqlserver_data:
    driver: local
